### ISSUE TITLE
Resolve "Node.js 12 actions are deprecated" CI warning

### ISSUE THREAD

**Issue by sshine** [sshine/simplex-desktop#3]
The CI workflow depends on [`actions-rs/toolchain`](https://github.com/actions-rs/toolchain) to install the Rust toolchain:

```yaml
      - name: Install stable toolchain + additional wasm target
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.7, 2020-03-24
        with:
          target: wasm32-unknown-unknown
          profile: minimal
          toolchain: stable
          override: true
```

Unfortunately, this action depends on Node 12.0, which [GitHub marked as deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) September 2022:

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791, actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

There is not a final date for deprecating Node 12.0 yet:

> We will monitor the progress of the migration and listen to the community for how things are going before we define a final date.

Whether `actions-rs/toolchain` upgrades to Node 16.0 is being tracked here:

- https://github.com/actions-rs/toolchain/issues/219

The worst case is that GitHub deprecates Node 12.0 before `actions-rs/toolchain` bumps their dependency; at this point we can quickly switch to one of the alternatives suggested in the upstream tracking issue. Those involve `curl ... | sh`, so they probably don't cache as well.

**This issue can be closed when those warnings are resolved.**
